# Generated by Django 4.0.1 on 2022-01-31 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=24)),
                ('manager_code', models.IntegerField()),
                ('mobile_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager', models.BooleanField(default=False)),
                ('is_agent', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=24)),
                ('mobile_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('linkein_link', models.CharField(blank=True, max_length=24)),
                ('github_link', models.CharField(blank=True, max_length=24)),
                ('website_link', models.CharField(blank=True, max_length=24)),
                ('per_10th', models.IntegerField()),
                ('per_12th', models.IntegerField()),
                ('stream', models.CharField(max_length=24)),
                ('fresher_expiriance', models.CharField(choices=[('Fresher', 'Expiriance')], max_length=24)),
                ('agent_socialmedia', models.CharField(choices=[('Agent', 'Social_media')], max_length=24)),
                ('status', models.CharField(default='In Progress', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=24)),
                ('year_of_experience', models.IntegerField()),
                ('work', models.TextField()),
                ('domain', models.CharField(max_length=24)),
                ('salary', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiance', to='data.useremployee')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=24)),
                ('collage_name', models.CharField(max_length=24)),
                ('cgpa', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='data.useremployee')),
            ],
        ),
        migrations.CreateModel(
            name='AgentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=24)),
                ('agent_code', models.CharField(max_length=24)),
                ('agent_mobile', models.IntegerField()),
                ('manager_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiance', to='data.managerdata')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.useremployee')),
            ],
        ),
    ]
