# Generated by Django 4.0.1 on 2022-02-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_agentmanager_alter_useremployee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='cgpa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='salary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='per_10th',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='per_12th',
            field=models.FloatField(null=True),
        ),
    ]
