# Generated by Django 4.0.1 on 2022-02-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_education_cgpa_alter_experience_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmanager',
            name='post',
            field=models.CharField(choices=[('Manager', 'Agent')], default=1, max_length=24),
            preserve_default=False,
        ),
    ]
