# Generated by Django 4.0.1 on 2022-02-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_agentmanager_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremployee',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useremployee',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agentmanager',
            name='post',
            field=models.CharField(choices=[(1, 'Manager'), (2, 'Agent')], max_length=24),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='agent_socialmedia',
            field=models.CharField(choices=[(1, 'Agent'), (2, 'Social_media')], max_length=24),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='fresher_expiriance',
            field=models.CharField(choices=[(1, 'Fresher'), (2, 'Manager')], max_length=24),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='per_10th',
            field=models.FloatField(null=True, verbose_name='10th %'),
        ),
    ]
