# Generated by Django 4.0.1 on 2022-02-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_useremployee_is_agent_useremployee_is_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremployee',
            name='per_12th',
            field=models.FloatField(null=True, verbose_name='12th %'),
        ),
    ]
