# Generated by Django 4.0.1 on 2022-02-03 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_useremployee_fresher_expiriance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('fresher_expiriance', models.CharField(choices=[(1, 'Fresher'), (2, 'Experience')], max_length=24)),
                ('agent_socialmedia', models.CharField(choices=[(1, 'Agent'), (2, 'Social_media')], max_length=24)),
            ],
        ),
        migrations.RemoveField(
            model_name='useremployee',
            name='agent_socialmedia',
        ),
        migrations.RemoveField(
            model_name='useremployee',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='useremployee',
            name='fresher_expiriance',
        ),
        migrations.RemoveField(
            model_name='useremployee',
            name='per_10th',
        ),
        migrations.RemoveField(
            model_name='useremployee',
            name='per_12th',
        ),
        migrations.RemoveField(
            model_name='useremployee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='useremployee',
            name='stream',
        ),
        migrations.AddField(
            model_name='education',
            name='per_10th',
            field=models.FloatField(null=True, verbose_name='10th %'),
        ),
        migrations.AddField(
            model_name='education',
            name='per_12th',
            field=models.FloatField(null=True, verbose_name='12th %'),
        ),
        migrations.AddField(
            model_name='education',
            name='stream',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='collage_name',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_name',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='agentmanager',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agentmanager', to='data.applications'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='data.applications'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiance', to='data.applications'),
        ),
    ]
