# Generated by Django 4.0.1 on 2022-02-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_applications_remove_useremployee_agent_socialmedia_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applications',
            new_name='Applicant',
        ),
    ]
